version: "3.6"
networks:
  mongodb_net:
services:
    birds-api:
        build:
            context: .
            dockerfile: ./deploy/Dockerfile.api
        ports:
            - 10001:80
        depends_on:
            - birds-db
        environment:
          - AppSettings__MongoConnectionString=$AppSettings__MongoConnectionString
          - ASPNETCORE_ENVIRONMENT=$ASPNETCORE_ENVIRONMENT
        networks:
            - mongodb_net
    birds-spa:
        build:
            context: .
            dockerfile: ./deploy/Dockerfile.spa
        ports:
            - 10003:80
        depends_on:
            - birds-api
        networks:
            - mongodb_net
    birds-db:
        image: mongo:latest
        networks:
            - mongodb_net
        ports:
            - 27017:27017
        environment:
            MONGO_INITDB_DATABASE: birds
