FROM node:latest AS base
WORKDIR /src

COPY bird-aggregator-client/package.json .
COPY bird-aggregator-client/tsconfig.json .
 
RUN npm install
RUN npm rebuild node-sass

COPY bird-aggregator-client/. .
RUN npm run build

FROM nginx:latest
COPY --from=base build /usr/share/nginx/html
EXPOSE 5005