FROM node:16 AS base
WORKDIR /src

COPY bird-aggregator-client/package.json .
COPY bird-aggregator-client/tsconfig.json .

RUN npm install

COPY bird-aggregator-client/. .
RUN npm run build

FROM nginx:latest
COPY --from=base /src/build /usr/share/nginx/html

EXPOSE 80 443